type CBS_Event = 
'abort' |
'activate' |
'addstream' |
'addtrack' |
'afterprint' |
'afterscriptexecute' |
'animationcancel' |
'animationend' |
'animationiteration' |
'animationstart' |
'appinstalled' |
'audioend' |
'audioprocess' |
'audiostart' |
'auxclick' |
'beforeinput' |
'beforeprint' |
'beforescriptexecute' |
'beforeunload' |
'beginEvent' |
'blocked' |
'blur' |
'boundary' |
'bufferedamountlow' |
'cancel' |
'canplay' |
'canplaythrough' |
'change' |
'click' |
'close' |
'closing' |
'complete' |
'compositionend' |
'compositionstart' |
'compositionupdate' |
'connect' |
'connectionstatechange' |
'contentdelete' |
'contextmenu' |
'copy' |
'cuechange' |
'cut' |
'datachannel' |
'dblclick' |
'devicechange' |
'devicemotion' |
'deviceorientation' |
'DOMActivate' |
'DOMContentLoaded' |
'DOMMouseScroll' |
'drag' |
'dragend' |
'dragenter' |
'dragleave' |
'dragover' |
'dragstart' |
'drop' |
'durationchange' |
'el.append' |
'el.appendChild' |
'el.change' |
'el.clear' |
'el.clone' |
'el.destroy' |
'el.hide' |
'el.removeChild' |
'el.render' |
'el.show' |
'emptied' |
'end' |
'ended' |
'endEvent' |
'enterpictureinpicture' |
'error' |
'focus' |
'focusin' |
'focusout' |
'formdata' |
'fullscreenchange' |
'fullscreenerror' |
'gamepadconnected' |
'gamepaddisconnected' |
'gatheringstatechange' |
'gesturechange' |
'gestureend' |
'gesturestart' |
'gotpointercapture' |
'hashchange' |
'hidden.bs.carousel' |
'hidden.bs.collapse' |
'hidden.bs.dropdown' |
'hidden.bs.modal' |
'hidden.bs.popover' |
'hidden.bs.tab' |
'hidden.bs.toast' |
'hidden.bs.tooltip' |
'icecandidate' |
'icecandidateerror' |
'iceconnectionstatechange' |
'icegatheringstatechange' |
'input.add' |
'input.save' |
'input' |
'inputsourceschange' |
'install' |
'invalid' |
'keydown' |
'keypress' |
'keyup' |
'label.add' |
'languagechange' |
'leavepictureinpicture' |
'load' |
'loadeddata' |
'loadedmetadata' |
'loadend' |
'loadstart' |
'lostpointercapture' |
'mark' |
'merchantvalidation' |
'message' |
'messageerror' |
'mousedown' |
'mouseenter' |
'mouseleave' |
'mousemove' |
'mouseout' |
'mouseover' |
'mouseup' |
'mousewheel' |
'mute' |
'negotiationneeded' |
'nomatch' |
'notificationclick' |
'offline' |
'online' |
'open' |
'orientationchange' |
'pagehide' |
'pageshow' |
'parameter.read' |
'parameter.write' |
'paste' |
'pause' |
'payerdetailchange' |
'paymentmethodchange' |
'play' |
'playing' |
'pointercancel' |
'pointerdown' |
'pointerenter' |
'pointerleave' |
'pointerlockchange' |
'pointerlockerror' |
'pointermove' |
'pointerout' |
'pointerover' |
'pointerup' |
'popstate' |
'progress' |
'push' |
'pushsubscriptionchange' |
'ratechange' |
'readystatechange' |
'rejectionhandled' |
'removestream' |
'removetrack' |
'removeTrack' |
'repeatEvent' |
'reset' |
'resize' |
'resourcetimingbufferfull' |
'result' |
'resume' |
'scroll' |
'search' |
'seeked' |
'seeking' |
'select' |
'selectedcandidatepairchange' |
'selectend' |
'selectionchange' |
'selectstart' |
'shippingaddresschange' |
'shippingoptionchange' |
'shown.bs.carousel' |
'shown.bs.collapse' |
'shown.bs.dropdown' |
'shown.bs.modal' |
'shown.bs.popover' |
'shown.bs.tab' |
'shown.bs.toast' |
'shown.bs.tooltip' |
'signalingstatechange' |
'slid.bs.carousel' |
'slide.bs.carousel' |
'slotchange' |
'soundend' |
'soundstart' |
'speechend' |
'speechstart' |
'squeeze' |
'squeezeend' |
'squeezestart' |
'stalled' |
'start' |
'statechange' |
'storage' |
'submit' |
'success' |
'suspend' |
'timeout' |
'timeupdate' |
'toggle' |
'tonechange' |
'touchcancel' |
'touchend' |
'touchmove' |
'touchstart' |
'track' |
'transitioncancel' |
'transitionend' |
'transitionrun' |
'transitionstart' |
'unhandledrejection' |
'unload' |
'unmute' |
'upgradeneeded' |
'versionchange' |
'visibilitychange' |
'voiceschanged' |
'volumechange' |
'vrdisplayactivate' |
'vrdisplayblur' |
'vrdisplayconnect' |
'vrdisplaydeactivate' |
'vrdisplaydisconnect' |
'vrdisplayfocus' |
'vrdisplaypointerrestricted' |
'vrdisplaypointerunrestricted' |
'vrdisplaypresentchange' |
'waiting' |
'webglcontextcreationerror' |
'webglcontextlost' |
'webglcontextrestored' |
'webkitmouseforcechanged' |
'webkitmouseforcedown' |
'webkitmouseforceup' |
'webkitmouseforcewillbegin' |
'wheel';